<!--Response popup-->
<div id="modal-content" class="modal fade" tabindex="-1" role="dialog">
    <div class="vertical-alignment-helper">
        <div class="modal-dialog vertical-align-center">
            <div class="modal-content">
                <div class="modal-body">
                    <div id="waiting">
                        <img src="<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif') ?>" class="text-center center-block"/>
                        <p class="text-center"><?php echo $this->__('Please wait until the product will be added.') ?></p>
                    </div>
                    <div id="response">
                        <p>&nbsp;</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>